[build-system]
requires = ["setuptools>=40.9.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ucr_tools"
version = "0.1"
dependencies = [
    "pandas>=2.0",
    "xlrd>= 2.0.1"
]

